drop database if exists srag_db;

create database srag_db;

create table dados_atendimento (
    dados_atendimento_pk serial primary key,
    usou_antiviral character varying (255),
    tipo_antiviral_utilizado character varying (255),
    descricao_outro_antiviral character varying (255),
    data_inicio_tratamento date,
    houve_internacao character varying (255),
    data_internacao_srag date,
    uf_internacao character varying (255),
    municipio_internacao character varying (255),
    codigo_ibge_internacao character varying (255),
    nome_regional_internacao character varying (255),
    codigo_regional_internacao character varying (255),
    internado_uti character varying (255),
    data_entrada_uti date,
    data_saida_uti date,
    tipo_suporte_ventilatorio character varying (255),
    tipo_raio_x_torax character varying (255),
    descricao_raio_x_torax character varying (255),
    data_raio_x date,
    aspecto_tomografia character varying (255),
    descricao_aspecto_tomografia character varying (255),
    data_tomografia date,
    coletou_amostra character varying (255),
    data_coleta date,
    tipo_amostra character varying (255),
    descricao_amostra character varying (255)
);


create table dados_clinicos_epidemiologicos (
    dados_clinicos_epidemiologicos_pk serial primary key,
    historico_viagem_internacional character varying (255) not null,
    pais_viagem character varying (255),
    codigo_pais_viagem character varying (255),
    local_viagem character varying (255),
    data_viagem date,
    data_retorno_viagem date,
    sg_evoluiu_srag character varying (255),
    caso_nosocomial character varying (255),
    contato_ave_suino_outro character varying (255),
    outro_animal character varying (255),
    febre character varying (255),
    tosse character varying (255),
    dor_garganta character varying (255),
    dispneia character varying (255),
    desconforto_respiratorio character varying (255),
    saturacao_dioxigênio character varying (255),
    diarreia character varying (255),
    vomito character varying (255),
    dor_abdominal character varying (255),
    fadiga character varying (255),
    perda_ofato character varying (255),
    perda_paladar character varying (255),
    outros_sintomas character varying (255),
    descricao_outros_sintomas character varying (255),
    puerpera character varying (255),
    fator_de_risco character varying (255),
    doenca_cardiovascular character varying (255),
    doenca_hematologica character varying (255),
    sindrome_de_down character varying (255),
    doenca_hepatica character varying (255),
    asma character varying (255),
    diabetes character varying (255),
    doenca_neurologica character varying (255),
    pneumopatia character varying (255),
    imunodeficiencia character varying (255),
    doenca_renal character varying (255),
    obesidade character varying (255),
    imc_paciente character varying (255),
    outros_fatores_risco character varying (255),
    descricao_fatores_risco character varying (255),
    vacinado_gripe character varying (255),
    data_ultima_dose_vacinaca_gripe date,
    mae_vacinada character varying (255),
    data_vacinacao_mae date,
    amamentando character varying (255),
    data_dose_unica date,
    data_primeira_dose date,
    data_segunda_dose date
);

create table dados_conclusivos (
    dados_conclusivos_pk serial primary key,
    classificacao_final_caso character varying (255),
    outro_agente_srag character varying (255),
    criterio_encerramento character varying (255),
    evolucao_caso character varying (255),
    data_alta_ou_obito date,
    data_encerramento date
);

create table dados_paciente (
    dados_paciente_pk serial primary key,
    sexo character varying (255) not null,
    data_nascimento date,
    idade character varying (255) not null,
    tipo_idade character varying (255) not null,
    tipo_idade_gestacional character varying (255),
    raca character varying (255),
    etnia_indigena character varying (255),
    escolaridade character varying (255),
    cod_classificacao_brasileira_ocupacao character varying (255),
    desc_classificacao_brasileira_ocupacao character varying (255)
);

create table dados_residencia_paciente (
    dados_residencia_paciente_pk serial primary key,
    uf_paciente character varying (255) not null,
    nome_regional_saude character varying (255),
    cod_regional_saude character varying (255),
    nome_municipio character varying (255) not null,
    cod_municipio character varying (255) not null,
    zona character varying (255),
    pais character varying (255) not null,
    codigo_pais character varying (255) not null
);

create table dados_laboratoriais (
    dados_laboratoriais_pk serial primary key,
    tipo_teste_antigenico character varying (255),
    data_resultado_antigeno date,
    resultado_teste_antigenico character varying (255),
    teste_antigenico_positivo_influenza character varying (255),
    an_influenza_resultado character varying (255),
    an_positivo_outros_virus character varying (255),
    an_positivo_sars_cov2 character varying (255),
    an_positivo_virus_sincicial_respiratorio character varying (255),
    an_positivo_parainfluenza1 character varying (255),
    an_positivo_parainfluenza2 character varying (255),
    an_positivo_parainfluenza3 character varying (255),
    an_positivo_adenovirus character varying (255),
    an_positivo_outro_virus character varying (255),
    an_descricao_outro_virus character varying (255),
    resultado_rtpcr character varying (255),
    data_resultado_rtpcr date,
    agente_rtpcr_positivo_influenza character varying (255),
    influenza_agt_rtpcr character varying (255),
    sub_tipo_influenza_a character varying (255),
    descricao_sub_tipo_influenza_a character varying (255),
    linhagem_influenza_b character varying (255),
    descricacao_linhagem_influenza_b character varying (255),
    rtpcr_positivo_outros_virus character varying (255),
    rtpcr_positivo_sars_cov2 character varying (255),
    rtpcr_positivo_sincicial_respiratorio character varying (255),
    rtpcr_positivo_parainfluenza1 character varying (255),
    rtpcr_positivo_parainfluenza2 character varying (255),
    rtpcr_positivo_parainfluenza3 character varying (255),
    rtpcr_positivo_parainfluenza4 character varying (255),
    rtpcr_positivo_adenovirus character varying (255),
    rtpcr_positivo_metapneumovirus character varying (255),
    rtpcr_positivo_bocavirus character varying (255),
    rtpcr_positivo_rinovirus character varying (255),
    rtpcr_positivo_outro character varying (255),
    descricao_rtpcr_outro character varying (255),
    tipo_amostra_sars_cov2 character varying (255),
    descricao_amostra_sars_cov2 character varying (255),
    data_coleta_amostra_sars_cov2 date,
    tipo_sorologia_sars_cov2 character varying (255),
    descricao_outro_sorologia_sars_cov2 character varying (255),
    resultado_sars_cov2_igg character varying (255),
    resultado_sars_cov2_igm character varying (255),
    resultado_sars_cov2_iga character varying (255),
    data_resultado_sars_cov2 date
);

create table dados_ficha (
    dados_ficha_pk serial primary key,
    data_preenchimento_ficha_notificacao date not null,
    semana_epidemiologica character varying (255),
    data_primeiros_sintomas date not null,
    semana_epidemiologica_primeiros_sintomas character varying (255),
    uf_posto_notificacao character varying (255) not null,
    nome_regional_saude character varying (255),
    codigo_regional_saude character varying (255),
    municipio_posto_notificacao character varying (255) not null,
    codigo_ibge_posto_notificacao character varying (255),
    nome_unidade_saude_notificacao character varying (255),
    codigo_cnes_posto_notificacao character varying (255) not null,
    dados_atendimento_pk integer,
    dados_clinicos_epidemiologicos_pk integer,
    dados_conclusivos_pk integer,
    dados_laboratoriais_pk integer,
    dados_paciente_pk integer,
    dados_residencia_paciente_pk integer,
    constraint fk_dados_atendimento foreign key (dados_atendimento_pk) references dados_atendimento(dados_atendimento_pk) on delete cascade,
    constraint fk_dados_clinicos_epidemiologicos foreign key (dados_clinicos_epidemiologicos_pk) references dados_clinicos_epidemiologicos(dados_clinicos_epidemiologicos_pk) on delete cascade,
    constraint fk_dados_conclusivos foreign key (dados_conclusivos_pk) references dados_conclusivos(dados_conclusivos_pk) on delete cascade,
    constraint fk_dados_laboratoriais foreign key (dados_laboratoriais_pk) references dados_laboratoriais(dados_laboratoriais_pk) on delete cascade,
    constraint fk_dados_paciente foreign key (dados_paciente_pk) references dados_paciente(dados_paciente_pk) on delete cascade,
    constraint fk_dados_residencia_paciente foreign key (dados_residencia_paciente_pk) references dados_residencia_paciente(dados_residencia_paciente_pk) on delete cascade
);
